# Configures pre-commit hooks for this repository
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # specific nbdev hooks, cleans notebooks
  - repo: https://github.com/fastai/nbdev
    rev: 2.3.13
    hooks:
      - id: nbdev_clean

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.10
    hooks:
      # run the linter with the .ruff.toml file for config
      # fix all fixable errors
      # - id: ruff
      #   args: [".", "--config", ".ruff.toml", "--fix"]

      #   # run the formatter with the .ruff.toml file for config
      - id: ruff-format
        args: [".", "--config", ".ruff.toml"]

  # export the relevant files as modified by ruff
  - repo: https://github.com/fastai/nbdev
    rev: 2.3.13
    hooks:
      - id: nbdev_export
