# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/tsfeatures_r.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/tsfeatures_r.ipynb 3
from typing import List

import pandas as pd
import rpy2.robjects as robjects
from rpy2.robjects import pandas2ri
