name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest] #[macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          # r-version: "4.3.3"
          install-r: false # If “false” use the existing installation in the GitHub Action image
          update-rtools: true # Update rtools40 compilers and libraries to the latest builds.

      - name: Check R Installation
        run: R --version
        shell: pwsh

      - name: Set up environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the library
        run: pip install ".[dev]"

      - name: Run tests
        run: nbdev_test --do_print --timing
